name: Validate api entries

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, review_requested, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: scrapiyard
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
          cache-dependency-path: ./scrapiyard
      - name: Run dump script
        working-directory: scrapiyard
        run: |-
          npm i @that-hatter/scrapi-factory
          npx dump -- --printErr
